### ISSUE TITLE
Nested object of collected keys

### ISSUE THREAD

**Issue by alxmiron** [grassator/webpack-extract-translation-keys#10]
In my project translation keys have scopes and written in form `module.namespace.key`. Using this plugin, I collect json file with content
```
{  'module.namespace.key': 'module.namespace.key' }
```
but for better usage, I would like to get
```
{
  module: {
    namespace: {
       key: 'module.namespace.key'
    }
  }
}
```
What do you think about this feature? I'm ready to contribute

**Comment by grassator** [comment]
Due to some legacy requirements of the system that this was originally built for, such a nested structure would not work, but if you can put it behind an optional flag with defaults staying what they are, I would be OK accepting the PR.

Another thing to think about is that this approach may have weird interaction with key mangling, so before the PR would be great to hear your thoughts on how that would work.

**Comment by alxmiron** [comment]
Think we will get more troubles than benefits. `.split('.')` helps me for now
